---
# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  # Number of characters
  line_length: 120
  # Allow long code blocks
  code_blocks: false
  # Allow long tables
  tables: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allow specific HTML elements
  allowed_elements: ["br"]

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041: false