---
name: Super-Linter

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      pull-requests: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Run Super Linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # ASCII Possum is cute, but not necessary
          SUPPRESS_POSSUM: true
          # Only check new or modified files
          VALIDATE_ALL_CODEBASE: false
          # Language-specific linters
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          # Misc configuration
          ENFORCE_COMMITLINT_CONFIGURATION_CHECK: true
          VALIDATE_GIT_COMMITLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          # Do not rely on the statuses permission
          MULTI_STATUS: false
